### ISSUE TITLE
Repo CI status icon links to one provider even when multiple are enabled

### ISSUE THREAD

**Issue by Zac-HD** [bfred-it/github-issue-link-status#10]
For https://github.com/HypothesisWorks/hypothesis-python this goes to Appveyor.  Contrast Github's default behaviour in this case - it pops up a little box with the status and details of each provider, with individual links.  Matching this behaviour would be really nice.

**Comment by fregante** [comment]
Are you confusing this with Refined GitHub?

**Comment by Zac-HD** [comment]
Gah, yes.  Sorry!
