### ISSUE TITLE
Not working in Firefox Quantum

### ISSUE THREAD

**Issue by heruan** [bfred-it/github-issue-link-status#12]
Seems like the Firefox add-on isn't working: I've installed it correctly but I see normal links.

**Comment by jdreesen** [comment]
Works for me on Win 10 with FF 57.0.4.

Did you set the GitHub API token in the plugin options?

**Comment by heruan** [comment]
Maybe the token it's the problem: when I set it it's green, but then when the field loses focus the token disappears. How can I know if it is set or not?

![issue-link-status-o](https://user-images.githubusercontent.com/851745/35030426-2ea8297a-fb5f-11e7-8d33-d4b0b871984b.gif)
(Fake token here, but the same happens with the real one.)

**Comment by fregante** [comment]
I don't know what could possibly clear the field, the extension does not edit the field in any way. It looks like a browser bug.

1. What Firefox/OS version are you using exactly?
2. Does it disappear when you click out or when you refresh the page?

Perhaps try opening `about:profiles` and trying with a fresh profile.

**Comment by heruan** [comment]
Fixed with fresh profile, thank you! (FF 57.0.4 macOS High Sierra, token was disappearing when pressing <kbd>ENTER</kbd> or refreshing the page.)

**Comment by heruan** [comment]
Reopening this, since the token value keeps disappearing. I suspect it disappears when syncing the account.

**Comment by adamyonk** [comment]
I'm seeing an issue in FF dev edition where it seems like the maxlength for that token field is one character less than what my newly generated token is - not sure if that is related to this.

**Comment by fregante** [comment]
@adamyonk that could explain why it happens — the value isn't saved unless it's "valid" — but in the GIF above the field turns green (with 40 characters) so it appears to be valid (yet not saved)

This line defines its validity:

https://github.com/bfred-it/github-issue-link-status/blob/18427058405504b1dad4fff2a77f238b8220477c/source/options.html#L39

Are you sure that the token is longer than 40? Or that the field accepts less than 40?

**Comment by heruan** [comment]
Now the behavior is different from the GIF: the value is saved and the add-on works, but eventually it stops working and in the settings the field is empty again and I have to refill it.

I’ll investigate more thoroughly testing sync since I suspect this happens when the settings are synced with the cloud (could it be? I’m not a Firefox add-on developer so it’s just empirical assumptions).

**Comment by adamyonk** [comment]
@bfred-it Aha! I went to check the length of the token I was getting from GH, and if you double-click it and copy, it copies with a space at the beginning - that's why it was clipping for me. Fixing that issue allowed me to add a token successfully.

I'll keep an eye on it to see if it is getting removed like what @heruan is seeing.

**Comment by fregante** [comment]
I tried in Fx 58, Fx 59 and Fx Dev 59.0b8 and it always seems to work, so it's hard for me to fix to this issue unless someone else can figure out what's happening. I could dismiss it by being a Firefox (Sync?) bug (because that's what it appears to be) but I wish I could solve it.

Are you using this view?

<img width="1190" alt="" src="https://user-images.githubusercontent.com/1402241/36106844-fc0e14c4-104a-11e8-819d-cc4ef56954d4.png">

**Comment by fregante** [comment]
You should see this in the developer tools:

![a](https://user-images.githubusercontent.com/1402241/36107023-769b10a2-104b-11e8-95bc-dca9fda28a3e.gif)

**Comment by fregante** [comment]
> if you double-click it and copy

Don't do that, there's a dedicated copy button 😅 

<img width="640" alt="copy button, but fake token" src="https://user-images.githubusercontent.com/1402241/36107206-ef13bc82-104b-11e8-92c8-f30696816a63.png">

**Comment by heruan** [comment]
In the console I see this every time I change the token:
```
Set option token to xxx                                                   options.js:147:5
Saving option token to xxx                                                options.js:184:3
Empty string passed to getElementById().                                 browser.xml:278:7
```
But then it works as expected. I'll try to sync on a new device and see if it disappears or not!

**Comment by fregante** [comment]
@heruan is it still working?

**Comment by heruan** [comment]
Well, I've not experienced the issue anymore but I also didn't have the chance to investigate further (e.g. testing after syncing on new devices). Feel free to close this if nobody else is affected!

**Comment by fregante** [comment]
Closing for now, thanks :)
