### ISSUE TITLE
Add ability to customize colours

### ISSUE THREAD

**Issue by DougEdey** [bfred-it/github-issue-link-status#15]
Currently the colours aren't very accessible for those with colour vision deficiencies

I'd like to see if there's a way to customize them from the settings (I may poke and explore it myself)

**Comment by fregante** [comment]
The colors are GitHub's own colors and classes. You can override them across the site with Stylus, targeting the classes `.text-green`, `.text-red`, and `.text-purple`, perhaps together with `.ILS`:


```css
.ILS.text-green {
  color: blue;
}
```
