### ISSUE TITLE
Style applied to PR view changes button & file link

### ISSUE THREAD

**Issue by Mottie** [bfred-it/github-issue-link-status#2]
Within a currently open PR ([ref](https://github.com/openstyles/stylus/pull/62#pullrequestreview-36534435)), the "view changes" button and file name link is being targeted by the extension

![pr](https://user-images.githubusercontent.com/136959/34174071-4b74ae10-e4bd-11e7-9844-d346de8863c9.gif)

Errr, unless that was intentional... targeting itself?

**Comment by fregante** [comment]
Thank you for the report! Fixed :)

**Comment by fregante** [comment]
This change also made it apply to any markdown area, like the readme. 

Try here: https://github.com/sindresorhus/refined-github

How does it look?

**Comment by Mottie** [comment]
Very awesome!

I wonder though... how would it handle a link around an image....

[![Wizard-Clap-by-Markus-Magnusson](https://user-images.githubusercontent.com/136959/34175869-75391ce4-e4c3-11e7-836d-96af7b6c55d2.gif)](https://github.com/bfred-it/github-issue-link-status/issues/2)
