### ISSUE TITLE
Add support for ~~#000~~

### ISSUE THREAD

**Issue by fregante** [bfred-it/github-issue-link-status#20]
`~~#1~~` is rendered as ~~#1~~ but this extension strips the `<del>` and its strikethrough.

More formatting that works correctly:
- [~~crossed~~](https://github.com/bfred-it/github-issue-link-status/issues/1)
- **#1**
- _#1_

**Comment by grahamperrin** [comment]
The extension works in Waterfox Classic 56.2.13 – thanks to Chrome Store Foxified – however the result is not monospaced: 



– and there are other issues, for example:
