### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [bfred-it/github-issue-link-status#24]
Hi, please consider including release notes – to be visible at https://addons.mozilla.org/addon/github-issue-link-status/versions/

**Comment by fregante** [comment]
Thanks but the release is automated and there’s no API for that

**Comment by grahamperrin** [comment]
https://github.com/fregante/github-issue-link-status/compare/20.4.26...20.5.27

**Comment by fregante** [comment]
Right, that’s on GitHub though; you suggested adding them to AMO, right?

**Comment by grahamperrin** [comment]
Yeah, it'll be smart to have notes at AMO. 

It's customary for the notes to be represented in a tab (alongside _Permissions_): 

![image](https://user-images.githubusercontent.com/192271/90520963-e51a3a00-e161-11ea-9894-dde370a31253.png)

https://github.com/fregante/github-issue-link-status/compare/20.5.27...20.8.16

**Comment by fregante** [comment]
Again, this is not currently possible via API as far as I know, and I’m not going to manually create release notes for every extension I have. 

When it becomes possible, I probably will.

**Comment by grahamperrin** [comment]
https://github.com/fregante/github-issue-link-status/compare/20.9.26...21.3.15

**Comment by fregante** [comment]
Why did you post that link?

**Comment by grahamperrin** [comment]
Just for convenience, as I had a bookmark for this issue

**Comment by fregante** [comment]
You can use https://github.com/fregante/github-issue-link-status/releases or bookmark https://github.com/fregante/github-issue-link-status/compare/20.9.8...master directly
