### ISSUE TITLE
support gh api token via firefox sync

### ISSUE THREAD

**Issue by staabm** [bfred-it/github-issue-link-status#25]
recently I had to setup a new device and used firefox sync to get all my extensions and browsing history/settings etc. across.

I was wondering, why I had to re-enter the github api access token again while https://github.com/sindresorhus/refined-github managed to sync the token with the firefox profile.

maybe thats a use case which could be supported?

**Comment by fregante** [comment]
I don’t know why you had to renter it, maybe it hadn’t finished syncing. I already use `browser.storage.sync` so there’s nothing else I can do
