### ISSUE TITLE
Support for draft PRs

### ISSUE THREAD

**Issue by yakov116** [bfred-it/github-issue-link-status#31]
Thanks for this awesome extension, been using it for about 2 years!

Would you be able to add support for draft Pr's and color them gray?

Thanks

**Comment by fregante** [comment]
The gray color makes the link almost disappear. Another solution is needed

**Comment by fregante** [comment]
Perhaps they should still be green, and just color the icon in gray

**Comment by fregante** [comment]
Closed draft: https://github.com/facebook/react/pull/19384
Open draft: https://github.com/facebook/react/pull/17669

**Comment by fregante** [comment]
<img width="296" alt="" src="https://user-images.githubusercontent.com/1402241/102663083-1b86b680-414e-11eb-8b83-31e2ad1b3375.png">
