### ISSUE TITLE
The CWS version is not the latest (as in repo and AMO)

### ISSUE THREAD

**Issue by darkred** [bfred-it/github-issue-link-status#35]
In [CWS](https://chrome.google.com/webstore/detail/github-issue-link-status/nbiddhncecgemgccalnoanpnenalmkic) the latest version is still 20.5.27 while in the repo and [AMO](https://addons.mozilla.org/en-US/firefox/addon/github-issue-link-status/) it's 20.8.16 .

*If it helps, I've been following this issue for npmhub, https://github.com/npmhub/npmhub/issues/108, and so I thought to check in Actions|[Deployment](https://github.com/fregante/github-issue-link-status/actions?query=workflow%3ADeployment)*:
I see that all its recent runs (after 20.5.27) all completed successfully.

**Comment by fregante** [comment]
I re-deployed. You should see 20.9.8 soon:



[badge-cws]: https://img.shields.io/chrome-web-store/v/nbiddhncecgemgccalnoanpnenalmkic.svg?label=
[badge-amo]: https://img.shields.io/amo/v/github-issue-link-status.svg?label=
[link-cws]: https://chrome.google.com/webstore/detail/github-issue-link-status/nbiddhncecgemgccalnoanpnenalmkic 'Version published on Chrome Web Store'
[link-amo]: https://addons.mozilla.org/en-US/firefox/addon/github-issue-link-status/ 'Version published on Mozilla Add-ons'


- [**Chrome** extension](https://chrome.google.com/webstore/detail/github-issue-link-status/nbiddhncecgemgccalnoanpnenalmkic) [![][badge-cws]][link-cws]
- [**Firefox** add-on](https://addons.mozilla.org/en-US/firefox/addon/github-issue-link-status/) [![][badge-amo]][link-amo]

**Comment by fregante** [comment]
Good to go!

**Comment by darkred** [comment]
Thank you very much!

**Comment by darkred** [comment]
@fregante 
The same has happened with the latest release, 21.3.15 :
In the latest [Release action](https://github.com/fregante/github-issue-link-status/actions/runs/653728190)
`Submit (firefox)` succeeded, but `Submit (chrome)` failed.
The [error](https://github.com/fregante/github-issue-link-status/runs/2111474054?check_suite_focus=true) :
> Publish condition not met: To publish your item, you must certify that your data usage complies with our Developer Program Policies. You can certify this on the Privacy practices tab of the item edit page of the Developer Dashboard.

_In CWS it's still 20.9.26 ._

**Comment by fregante** [comment]
Thanks for the report, once again. It's easy to miss failing GHA runs

**Comment by fregante** [comment]
It's been published now

**Comment by darkred** [comment]
The same has occurred again, now with release 21.9.3. The [error](https://github.com/fregante/github-issue-link-status/runs/3506063020?check_suite_focus=true) :

> Error Code: PKG_NO_TWO_FACTOR_AUTH
> Details: Enabling 2 step verification on your account is required for security purposes. Please visit google.com/landing/2step to set it up.

&nbsp;
Also, while the AMO (`Submit (firefox)`) Release action [succeeded](https://github.com/fregante/github-issue-link-status/runs/3506062972?check_suite_focus=true), it's still 21.6.8 .

**Comment by fregante** [comment]
Thanks for the report. I now fixed it for my account, but 21.9.3 won't be available for Chrome (it only has fixes for Firefox anyway)
