### ISSUE TITLE
Permissions at GitHub Enterprise

### ISSUE THREAD

**Issue by koppor** [bfred-it/github-issue-link-status#41]
The extension works great on github.com. It has following permissions:

![image](https://user-images.githubusercontent.com/1366654/102213788-8e3a2c80-3ed7-11eb-8fc0-93707da3c93d.png)

When using it on a GitHub Enterprise setting, I get following permissions:

![image](https://user-images.githubusercontent.com/1366654/102213820-9a25ee80-3ed7-11eb-8fd2-e11fe997f9f8.png)

Is this something the extension can handle or is this a browser-related issue?

Refs https://github.com/fregante/github-issue-link-status/pull/33

Oliver Kopp <oliver.kopp@mbition.io>, Mercedes-Benz AG on behalf of [MBition GmbH](https://mbition.io/).

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)

**Comment by fregante** [comment]
You should see “Enable X on this domain”


![](https://user-images.githubusercontent.com/1402241/32874388-e0c64150-cacc-11e7-9a50-eae3727fd3c2.png)

If it doesn’t appear, try disabling+reenabling the extension or restarting the browser.

**Comment by fregante** [comment]
I just tested it and it works. I think sometimes Chrome doesn't register the menu so you'll have to restart the browser or extension

<img width="802" alt="Screen Shot 2020-12-18 at 16 18 22" src="https://user-images.githubusercontent.com/1402241/102662419-cf874200-414c-11eb-835e-7d805854e773.png">

**Comment by koppor** [comment]
@fregante I checked today again. A click on "Enable on this Domain" does not change any rendering.

In the menu "This Can Read and Change Site Data", I cannot enable "On all web sites" (tried on private ChromeOS and on company-managed Windows installation). Could you share a screenshot of your submenu "This Can Read and Change Site Data" being opened?

For me, on github.com it is as follows:

![image](https://user-images.githubusercontent.com/1366654/111132956-43818c80-857a-11eb-99f6-190140767bef.png)

On an arbitrary page:

![image](https://user-images.githubusercontent.com/1366654/111133039-598f4d00-857a-11eb-976c-d611ea61ece5.png)

On google.com

![Screenshot 2021-03-15 at 10 37 05](https://user-images.githubusercontent.com/1366654/111133146-788ddf00-857a-11eb-8343-7ef115ea5ddb.png)

**Comment by fregante** [comment]
> In the menu "This Can Read and Change Site Data", I cannot enable "On all web sites"

That menu is unrelated, that's why I did not take a screenshot of it. Ignore it completely.

See the focused item in my last screenshot, can you see "Enable X on this domain" in English?

<img width="802" alt="Screen Shot 2020-12-18 at 16 18 22" src="https://user-images.githubusercontent.com/1402241/102662419-cf874200-414c-11eb-835e-7d805854e773.png">

Take a screenshot of the menu shown here, maybe I'll have a new update coming for it.

**Comment by fregante** [comment]
I just released a new version that might have a more reliable menu.

Updated to 21.3.15 in about an hour, you might manually update it via: https://support.kixie.com/hc/en-us/articles/235601588-How-to-Force-an-Update-of-Your-Chrome-Extensions

After installing version 21.3.15, try this:

1. Open a new tab 
2. Visit GitHub Enterprise domain and wait for it to finish loading

Can you see "Enable GitHub Issue Link Status on this domain" in the menu?

If not:

3. Open a new tab in the same window
4. Close the new tab
5. Open the previous tab with GitHub Enterprise

This should have triggered a refresh for the menu item.

If it still doesn't appear:

1. Take a screenshot of this menu like mine
2. Visit `chrome://inspect/#extensions`
3. Click "Inspect" on "GitHub Issue Link Status"
4. Take a screenshot of this new window
5. Post both screenshots here

**Comment by koppor** [comment]
Works fine now with `21.3.15`. Thank you for the effort!

**Comment by fregante** [comment]
Thanks for the update!
