### ISSUE TITLE
Append title after the issue

### ISSUE THREAD

**Issue by koppor** [bfred-it/github-issue-link-status#42]
This plugin makes it easy to obtain information on a linked issue without the user having to move the mouse, open new windows, etc. Having that in mind, following feature request is written.

I have following Pull Request description:

![grafik](https://user-images.githubusercontent.com/1366654/103639568-cec51d00-4f4e-11eb-8847-bc784d9f6124.png)

Now, I am asking myself, what the content of each issue is.

I can use my mouse and hover on each issue. Example:

![grafik](https://user-images.githubusercontent.com/1366654/103639627-e8fefb00-4f4e-11eb-956c-ff7ae8c9e6fe.png)

Can't the plugin also include the titles of the issues?

![grafik](https://user-images.githubusercontent.com/1366654/103639727-1a77c680-4f4f-11eb-84ba-ab5928cee165.png)

I checked https://github.com/stefanbuck/awesome-browser-extensions-for-github whether there is a plugin with that functionality, but I did not find one. Since this plugin already changes the issue link and already fetches data on the issue itself, it could be a good place to support that functionality. Thereby, I accepted that it is not just a "status" and thus broadens the scope of the plugin. Nevertheless since the wished functionality is IMHO close to the existing one, I have raised this feature request.

**Comment by fregante** [comment]
I considered this addition for when issue links appear at the end of a line, for example:

_Closes #3_

Or when they're just in a list (same logic):

- #1 
- #2 

Adding titles when they're in the middle of a sentence or if there's more than a link it can just cause noise. It makes no sense to add it _on hover_ because _on hover_ there's already the hover card.

**Comment by koppor** [comment]
Looks good - maybe also if the current line only covered by issue references (and non-letters; maybe "refs", "fixes")

* Fixes #1, #3, #3
* Refs #1, #2
* Not at: See also #1

Even if the last line would IMHO also make sense. -- Maybe, the rule is that if a line ends with an issue, it can be expaned, too?

**Comment by fregante** [comment]
FYI “fixes” only supports one link, GitHub won’t close multiple issues like that. You have to repeat “fixes” for every link. 

I think the problem generally are long titles. One long title can always go on a single line, but multiple titles probably can’t. I think my previous logic remains: one per line, if the line ends with it, at least as a default. 

I’d use a secondary API request for so this can be customized separately.

**Comment by fregante** [comment]
Implemented by GitHub in lists!! 🎉
