### ISSUE TITLE
New GitHub tokens are not accepted by the options form

### ISSUE THREAD

**Issue by fregante** [bfred-it/github-issue-link-status#45]
Not a bug yet, but soon it will be:

https://github.blog/changelog/2021-03-04-authentication-token-format-updates/

The new format isn't accepted by our form

**Comment by ckzhang26** [comment]
Hello, I'd like to work on this issue.  Is it still open and are you looking for someone to work on it right now?

**Comment by fregante** [comment]
Yes please, you can work on it! 🙂

**Comment by fregante** [comment]
The pattern used in the html file needs to be changed in this case

**Comment by ckzhang26** [comment]
Sounds good!  I will give it a shot.
