### ISSUE TITLE
Closed draft looks funny

### ISSUE THREAD

**Issue by yakov116** [bfred-it/github-issue-link-status#47]
![image](https://user-images.githubusercontent.com/16872793/111922044-26fbbd80-8a6e-11eb-9568-3596bd54c6ef.png)

If its closed it should be totally red

**Comment by fregante** [comment]
It’s a feature https://github.com/fregante/github-issue-link-status/issues/31#issuecomment-748328292

**Comment by yakov116** [comment]
Could we make an option....

.
.
.

Just kidding np thought it was a mistake
