### ISSUE TITLE
Enable in Preview tab of the editor

### ISSUE THREAD

**Issue by darkred** [bfred-it/github-issue-link-status#50]
I've noticed that the links are not colorized in the 'Preview' tab of the of issues/PR/discussions text editor:

<details>
<summary>screen capture</summary>

For example, in this page, I enter 2 links (a merged PR and a closed issue) and switch to the Preview tab, 
they are not colorized:

- PR (merged) : https://github.com/sindresorhus/refined-github/pull/3977
- issue (closed): https://github.com/sindresorhus/refined-github/issues/3975

![](https://user-images.githubusercontent.com/723651/113850061-be694c00-97a2-11eb-9533-3db4e54e4742.gif)
</details>

I believe that colorizing the links in the 'Preview' tab  would facilitate the user, to better visualize what their submission would be.

PS Using extension 21.4.1 (with API token) in Chrome 89/Firefox 87.

**Comment by darkred** [comment]
I've just made PR #55.

**Comment by darkred** [comment]
Hi @fregante. Have you checked my PR? Are you against, should I close it?
I am only asking because there have been two releases since I created this PR, and I haven't got any comment from you.

---

@yakov116 Could you please elaborate on why you are against this? I personally believe the extra queries are worth it.

**Comment by fregante** [comment]
I wouldn't be against it but catching the preview is difficult and the current PR is incomplete and not as efficient as it should be, and I'm not particularly interested in fixing it myself

**Comment by darkred** [comment]
Ok, thanks for replying. 
I thought it was complete, ready to merge... 
I'm sorry I can't bring this effort to completion. I'm closing the PR.

**Comment by darkred** [comment]
@fregante sorry, but if it's not too much to ask, could you please explain:
1. In which way is catching the preview difficult to achieve? 
2. Why do you find the PR incomplete and not as efficient as it should be? What's wrong with my approach?

I'd like to have clear in my mind what the optimal approach should be, I'd like to try to make it complete if I can.
I only ask for some generic guidelines.

**Comment by fregante** [comment]
- It calls onNewElements twice, and the second call is not called again on ajaxed pages
- it attached the event to every element separately instead of using a single event listener or event delegation

**Comment by darkred** [comment]
Could you please take a look in the PR again? I think I have followed all your points.

**Comment by yakov116** [comment]
> @yakov116 Could you please elaborate on why you are against this? I personally believe the extra queries are worth it.

The reason I don't think there is a need. 

1. GitHub shows a drop down when typing in an issue number, so you can see the issue status. 
2. I feel this will lead to many API requests.

**Comment by fregante** [comment]
That's a good point Yakov

**Comment by fregante** [comment]
https://github.com/fregante/github-issue-link-status/issues/50#issuecomment-913187288

**Comment by darkred** [comment]
@yakov116 Thanks for replying. 
I respect fregante's decision to close this issue and PR of course. 
I just wanted to clarify one thing regarding:

> * GitHub shows a drop down when typing in an issue number, so you can see the issue status.

I am aware of that feature (which only applies to issues/PRs of the *same* repo). 
But the reason I made this feature request was different: the aim was not to assist in the comment writing procedure, 
but to help the commenter visualize his comment the exact way it will be displayed when submitted, in cases when you have a lot of links in your comment, and when you have links to issues/PRs of different repos.
