### ISSUE TITLE
New GitHub token format not recognized

### ISSUE THREAD

**Issue by sheldonhull** [bfred-it/github-issue-link-status#53]
The newer token format providers more granular level permissions and starts with `ghp_`.
This was not recognized by the extension as a valid token, preventing me from generating and using a new token for the tool.

https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

**Comment by yakov116** [comment]
It should be 2eb0caed5752b267ae87c2a6e6912ff79e1675cb

What version are you on?

**Comment by sheldonhull** [comment]
> It should be [2eb0cae](https://github.com/fregante/github-issue-link-status/commit/2eb0caed5752b267ae87c2a6e6912ff79e1675cb)
> 
> What version are you on?

`21.3.15`

I see this is out of date. 
I have restarted but nothing refreshed. 
I've noticed some of these chrome updates are laggy despite being set to autoupdate and only uninstall and reinstall seems to force. 

Trying right now

**Comment by sheldonhull** [comment]
Ok, I had to download [Get CRX](https://chrome.google.com/webstore/detail/get-crx/dijpllakibenlejkbajahncialkbdkjc/related) and then download CRX and in extensions page drag it and it forced the update finally (clicking crx directly didn't do anything, neither did manual update requests)

This was recognized. Woot woot. Thank you for this helpful extension 💯
