### ISSUE TITLE
Help with building the extension

### ISSUE THREAD

**Issue by darkred** [bfred-it/github-issue-link-status#54]
Greetings

I'm trying to build the extension, in order to try adding support for the 'Preview' tab.

*(there are no build instructions in readme.md)*
<details>
<summary>For reference the <code>scripts</code> section of package.json is as follows:</summary>

```
"scripts": {
"build": "parcel build source/manifest.json --dist-dir distribution --no-cache --detailed-report 0",
"lint": "xo",
"test": "xo && npm run build",
"watch": "parcel watch source/manifest.json --dist-dir distribution --no-cache --no-hmr"
},
```
</details>

&nbsp;
So, I'm doing the following (using Node 16.0 x64 with win10) :

```
git clone https://github.com/fregante/github-issue-link-status
cd github-issue-link-status
npm install
npm run build  or  npm run watch
```

Then I sideload the extension (the produced `github-issue-link-status\distribution` directory) to a fresh profile of Chrome 90,
and I notice that the extension unfortunately doesn't work, i.e. it doesn't colorize issues and PRs.
Specifically:
- I'm getting in Console
    ```
    Uncaught ReferenceError: regeneratorRuntime is not defined
       at github-issue-link-status.js:1
    ```
- the v4 API token I generated specifically for this, is not stored when I reopen settings.

&nbsp;
Did I do something wrong? How can I fix this?
Thank you

**Comment by fregante** [comment]
Thanks for the issue. Strangely Babel is transpiling async/await to "regenerator" even if Firefox 52 supports them natively: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

I increased the minimum Firefox version and now it seems to work.

**Comment by darkred** [comment]
Yes, I confirm it works ok in both Firefox/Chrome. Thank you.
