### ISSUE TITLE
Triple issue icon with full issue link in an embedded code block linkified by refined github

### ISSUE THREAD

**Issue by altrisi** [bfred-it/github-issue-link-status#56]
Screenshot:

![imagen](https://user-images.githubusercontent.com/17107132/120222530-5eda6a80-c240-11eb-92a5-e9059add47b1.png)

Example url where this issue occurs: https://github.com/gradle/gradle/pull/17087

Doesn't happen without Refined Github since the url wouldn't be linkified.

Using Firefox if that matters.

**Comment by fregante** [comment]
Thank you for the report!

This is actually a Refined GitHub issue. Follow https://github.com/sindresorhus/refined-github/issues/3226
