### ISSUE TITLE
incorrect issue status icon

### ISSUE THREAD

**Issue by shinenelson** [bfred-it/github-issue-link-status#60]
the status icon for closed issues show up as open

![Screenshot_20210621_143439](https://user-images.githubusercontent.com/4771718/122738728-e0517580-d29f-11eb-8f27-95a8060842cf.png)

**Comment by fregante** [comment]
The demo page still works correctly for me in Chrome https://github.com/fregante/github-issue-link-status/issues/57

<img width="551" alt="Screen Shot 20" src="https://user-images.githubusercontent.com/1402241/122739214-f9145800-d2ac-11eb-928d-29a7d85d6467.png">


Make sure your token has not expired. Check the browser console.

**Comment by shinenelson** [comment]
It's weird actually, the token syncs across browsers ( in Firefox ). I have it working fine on Firefox Developer Edition but not on the standard Firefox. I noticed that token-based Refined GitHub features are also not enabled on my standard Firefox ( it could be an issue with the browser sync not working properly ). I don't use GitHub on my standard Firefox profile that much though. I will probably have to test this better locally.
