### ISSUE TITLE
Partially implemented by GitHub

### ISSUE THREAD

**Issue by kidonng** [bfred-it/github-issue-link-status#61]
I got an extra PR title and merged indicator in https://github.com/nix-community/home-manager/pull/2131:

![image](https://user-images.githubusercontent.com/44045911/123138483-a6db5e80-d487-11eb-8eb6-272cbcac59a9.png)

The same PR in a private browser window:

![image](https://user-images.githubusercontent.com/44045911/123138878-223d1000-d488-11eb-9e49-69ff446a4f12.png)

Turns out it is provided by GitHub. I'm not sure what's the criteria, haven't found any other one aside from this.

**Comment by fregante** [comment]
Maybe only merged PRs? The demo page isn’t affected https://github.com/fregante/github-issue-link-status/issues/57

**Comment by kidonng** [comment]
The demo page shows no icon.

A side note: I `https://quote.the.link` because it only serves as an example, I don't want to create an irrelevant reference on the original issue/PR. Admittedly this makes it non-clickable but I think the inconvenience is worth it. If you don't have particular reason, please keep it as-is (in the future), thanks!

**Comment by TimWolla** [comment]
See also this discussion: https://github.com/github/feedback/discussions/4260

**Comment by fregante** [comment]
I see that https://github.com/fregante/github-issue-link-status/issues/42 has also been implemented by GitHub so hopefully I can retire this extension soon!

My guess is that the demo page doesn’t work because it’s a table and some contexts maybe aren’t affected?

It appears to be part of https://github.com/features/issues

**Comment by fregante** [comment]
> but I think the inconvenience is worth it

@kidonng Not for me that I have to select the text, copy it, open the URL bar (mobile), paste it and go. It's just moving the annoyance from someone who _sees_ a linkback (in an empty PR) to _everyone_ who wants to visit the link you post. 🤷‍♂️

**Comment by fregante** [comment]
I opened an issue to limit this extension to the parts where it's not applied 👆

**Comment by kidonng** [comment]
> > but I think the inconvenience is worth it
> 
> @kidonng Not for me that I have to select the text, copy it, open the URL bar (mobile), paste it and go. It's just moving the annoyance from someone who _sees_ a linkback (in an empty PR) to _everyone_ who wants to visit the link you post. 🤷‍♂️ 

I know this is going off-topic, but I'd like to continue a little bit: let's use `togithub.com` next time: https://togithub.com/sindresorhus/refined-github/issues/4480#issuecomment-862357937

**Comment by fregante** [comment]
That's a good compromise! Thank you
