### ISSUE TITLE
Update to purple text for closed issues

### ISSUE THREAD

**Issue by Yash-Singh1** [bfred-it/github-issue-link-status#64]
GitHub updated their icons to be purple for closed.

![Screenshot from 2021-10-27 18-34-19](https://user-images.githubusercontent.com/53054099/139171066-b606c330-bddf-4aee-8136-335631a7e7ae.png)

**Comment by fregante** [comment]
PR welcome if you'd like

**Comment by Yash-Singh1** [comment]
Sure, I am working on this.
