### ISSUE TITLE
Extension leads to display problems in item TODO lists that are longer than 1 line

### ISSUE THREAD

**Issue by janpio** [bfred-it/github-issue-link-status#68]
Without extension:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/183673/161156927-552584a6-1abf-4133-a028-ad766ff67b7d.png">

With:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/183673/161156610-70e37541-f55a-40d3-92f6-9da0a17d6c19.png">

From https://github.com/prisma/prisma/issues/12367

**Comment by fregante** [comment]
Are you using the latest version? Those links should be excluded

**Comment by fregante** [comment]
Ah #62 hasn't been fixed yet. This is the same issue 😅

**Comment by janpio** [comment]
Ah ok, I did not make that connection. Thanks for the pointer.
