### ISSUE TITLE
Broken on AJAX navigation

### ISSUE THREAD

**Issue by tjx666** [bfred-it/github-issue-link-status#70]
## Description

When I jump to issue page <https://github.com/microsoft/vscode/issues/197438> from <https://github.com/microsoft/vscode/issues/> by click the pinned link, the links will not be colorized. But works after I refreash the page.

## Versions

browser: chrome 119.0.6045.159

https://github.com/fregante/github-issue-link-status/assets/41773861/bdf84ea9-e14e-4958-85c4-52db8d767e6d

**Comment by fregante** [comment]
Indeed. I'll look into this

**Comment by fregante** [comment]
Fixed by c4f49661859e2e8aacf15e1211e8e52e8805fa1b

Thank you for the report! I haven't used this extension for a while so it's been broken for probably a year 🥲 

I'll publish a new version soon

**Comment by tjx666** [comment]
Thanks your work open source

**Comment by darkred** [comment]
Thanks for fixing this, @fregante.

I noticed that the [action](https://github.com/fregante/github-issue-link-status/actions/runs/7150956951) of last week for publishing v23.12.9 to CWS failed with the following error:

<details>
<summary>Error in <code>Submit (Chrome)</code>:</summary>

[relevant workflow step](https://github.com/fregante/github-issue-link-status/actions/runs/7150956951/job/19474797120#step:4:24)

```
Run npx chrome-webstore-upload-cli@2 upload --auto-publish
npm WARN exec The following package was not found and will be installed: chrome-webstore-upload-cli@2.2.2
- Fetching token
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
Probably the provided refresh token is not valid. Try following the guide again
}
https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md
{
  clientId: '***',
  refreshToken: '***'
}
Error: Process completed with exit code 1.
```
</details>

**Comment by fregante** [comment]
Thank you! I manually uploaded the version to Chrome now
