### ISSUE TITLE
Support for multiple PATs on github.com

### ISSUE THREAD

**Issue by xt0rted** [bfred-it/github-issue-link-status#72]
I'm in an org that locks down PATs so only fine grained are allowed which means this extension doesn't work with it. Any way I set this up I lose link coloring somewhere.

This extension supports GitHub Enterprise which I was hoping would let me map one or more `github.com/:org` urls to their own PAT but it doesn't seem like that's possible right now. Could support for this be added in now that fine grained PATs are being used more and in some cases are the only way to work with an org?

**Comment by fregante** [comment]
> this extension doesn't work with it

It doesn't? It probably should. What happens when you use that?

**Comment by xt0rted** [comment]
I've been using a classic PAT since that has access to everything my account does, but since this org blocks classic PATs the extension can't load the issue & PR stats. It does load them for all issues/PRs outside of this org though.

Fine-grained tokens belong to the user or a single org so their scope is narrower than a classic token. I don't think they're that useful with this extension for that reason, but they are the only way to access some orgs now.

These are the settings found under `https://github.com/organizations/:org/settings/personal-access-tokens`. With the `Personal access token (classic)` setting set to restricted I only get icons added to my links for this org, but with it not restricted the links are also colored to match the status.

![image](https://github.com/fregante/github-issue-link-status/assets/831974/6f4be7c9-34be-4f50-a409-8c3cb155a906)

![image](https://github.com/fregante/github-issue-link-status/assets/831974/44832938-08ef-47cb-b1ac-bebabff5c2b7)

**Comment by fregante** [comment]
Refined GitHub doesn't support that either unfortunately:

- https://github.com/refined-github/refined-github/issues/6092#issuecomment-1732286938

Here are the complexities I'm not really interested in working on:

- accept multiple tokens in the options, one per organization
- splitting the API calls for each organization (currently this makes only one API call for all the links at once, regardless of where they appear)

I assume that public repos are steal _readable_ right? This is only an issue with private repos on organizations.

The only way I could work on this right now is probably if someone sponsors the entire effort
